name: Build App
 
on:
  push:
    tags:
      - '*'
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      with:
        submodules: recursive
            
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
     
    - name: Restore NuGet Packages
      run: nuget restore LostArkLogger.sln
      
    - name: Set Version
      id: ver
      run: |
        echo "::set-output name=version::$(echo ${Env:GITHUB_REF} | cut -d / -f 3)"
        
    - name: Build
      run: |
        dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false /p:Version=${{ steps.ver.outputs.version }}
      
    - name: Import PFX
      shell: powershell
      run: |
        $pfxCertFilePath = Join-Path -Path $PSScriptRoot -ChildPath "CodeSigningCertificate.pfx"
        Set-Content -Value $([System.Convert]::FromBase64String($env:BASE64_PFX)) -Path $pfxCertFilePath -Encoding Byte
        $codeSigningCert = Import-PfxCertificate -FilePath $pfxCertFilePath -Password $($env:PFX_PASSWORD | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation Cert:\CurrentUser\My
      env:
        BASE64_PFX: ${{ secrets.CERTIFICATE }}
        PFX_PASSWORD: ${{ secrets.PASSWORD }}

    - name: Sign exe
      shell: powershell
      run: |
        $codeSigningCert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
        Set-AuthenticodeSignature -Certificate $codeSigningCert -FilePath "bin\Release\net6.0-windows\win-x64\publish\DpsMeter.exe" -TimestampServer "http://timestamp.digicert.com"
        
    - name: Upload dll Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: DpsMeter.exe
        path: bin\Release\net6.0-windows\win-x64\publish\DpsMeter.exe

    - name: Add to releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          bin\Release\net6.0-windows\win-x64\publish\DpsMeter.exe